# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X7unxib3Cdji9SNljD6eqe7D2DD90eP_
"""

from scipy.stats import binom 
# setting the values 
# of n and p 
n = 2
p = 0.25

i_values = list(range(n + 1)) 
  

dist = [binom.pmf(i, n, p) for i in i_values ] 
 
print("i\tp(i)") 
for k in range(n + 1): 
    print(str(i_values[k]) + "\t" + str(dist[k]))