# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ehK02EaIDhujACWyJNouglk4i3-8P7PX
"""

from scipy.stats import binom 
# setting the values 
# of n and p 
n = 2
p = 0.25

X_values = list(range(n + 1)) 
  

dist = [binom.pmf(X, n, p) for X in X_values ] 
 
print("X\tp(X)") 
for k in range(n + 1): 
    print(str(X_values[k]) + "\t" + str(dist[k]))